debug: false
management:
  endpoints:
    web:
      exposure:
        include: "*"
    
logging:
  level:
    com.projectboard: debug
org.springframework.web.servlet: debug
org.hibernate.type.descriptor.sql.BasicBinder: trace

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/project_board?serverTimezone=Asia/Seoul
    username: lyg
    password: 2626
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    open-in-view: false
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 100
  h2:
    console:
      enabled: false
  sql:
    init:
      mode: always
  data:
    rest:
      base-path: /api
      detection-strategy: annotated
#  thymeleaf3:
#    decoupled-logic: true
        

      
      
      
      
      
      
      
      